name: Build RPCSX

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential libunwind-dev \
          libvulkan-dev vulkan-validationlayers \
          libsox-dev g++-14 ninja-build libasound2-dev libglfw3-dev nasm libudev-dev
        cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_INSTALL_PREFIX=/usr
        cmake --build build -j$(($(nproc) + 2))
        sudo cmake --build build

    - name: Build RPCSX
      run: |
        cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-14  -DCMAKE_CXX_FLAGS_INIT="-march=native"
        cmake --build build -j$(($(nproc) + 2))

    - name: Upload RPCSX
      uses: actions/upload-artifact@v4
      with:
        name: rpcsx-bin
        path: build/bin/*
        if-no-files-found: error
